tp_platform_home:
    path: /{page}
    defaults: {_controller: TickerPickerPlatformBundle:Advert:index, page: 1}
    requirements:
        page: \d*

tp_platform_view:
    path: /advert/{id}
    defaults: {_controller: TickerPickerPlatformBundle:Advert:view}
    requirements:
        id: \d*

tp_platform_add:
    path: /add
    defaults: {_controller: TickerPickerPlatformBundle:Advert:add}

tp_platform_edit:
    path: /edit/{id}
    defaults: {_controller: TickerPickerPlatformBundle:Advert:edit}
    requirements:
        id: \d*

tp_platform_delete:
    path: /delete/{id}
    defaults: {_controller: TickerPickerPlatformBundle:Advert:delete}
    requirements:
        id: \d*